name: Unit Tests
description: "Runs Relay's unit tests + linters and optionally gathers coverage."
inputs:
  lint:
    description: 'Whether to run linters.'
    required: false
    default: 'false'
  coverage:
    description: 'Whether to run coverage.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Get Go version
      id: go-version
      shell: bash
      run: |
        echo "version=$(go version | awk '{print $3}')" >> $GITHUB_OUTPUT
    - name: Lint
      if: inputs.lint == 'true'
      shell: bash
      run: make lint

    - name: Test
      if: inputs.coverage == 'false'
      shell: bash
      id: test
      run: make test | tee raw_report.txt

    - name: Process test results
      if: steps.test.outcome == 'success'
      id: process-test
      shell: bash
      run: go run github.com/jstemmer/go-junit-report@v0.9.1 < raw_report.txt > junit_report.xml

    - name: Test with coverage
      if: inputs.coverage == 'true'
      shell: bash
      id: test-coverage
      run: make test-coverage

    - name: Upload test results
      if: steps.process-test.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Test-result-${{ steps.go-version.outputs.version }}
        path: junit_report.xml

    - name: Upload coverage results
      if: steps.test-coverage.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Coverage-result-${{ steps.go-version.outputs.version }}
        path: build/coverage*
