project_name: ld-relay

run:
  deadline: 120s
  tests: false

linters:
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    #- lll  # no need to break up long lines at present
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  fast: false

linter-settings:
  gofmt:
    simplify: false

issues:
  exclude-rules:
    - path: integrationtests
      linters:
        - stylecheck
    - path: internal/metrics/measures.go  # see explanation in that file
      linters:
        - gochecknoglobals
    - path: internal/sharedtest/
      linters:
        - bodyclose
        - goconst
        - gochecknoglobals
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
