version: 2

project_name: ld-relay

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: ld-relay
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}`.
    ldflags:
      - -s -w -X internal.version.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - "7"

nfpms:
  - file_name_template: >-
      {{ .ConventionalFileName }}
    homepage: https://launchdarkly.com/
    maintainer: LaunchDarkly <team@launchdarkly.com>
    description: LaunchDarkly Stream Relay Proxy
    license: Apache 2.0
    vendor: Catamorphic Co.

    formats:
      - deb
      - rpm

    contents:
      - src: linux/etc/ld-relay.conf
        dst: /etc/ld-relay.conf
        type: config

      - src: linux/etc/init/ld-relay.conf
        dst: /etc/init/ld-relay.conf
        packager: deb

      - src: linux/etc/system/ld-relay.service
        dst: /usr/lib/systemd/system/ld-relay.service
        packager: rpm

    overrides:
      deb:
        dependencies:
          - upstart
      rpm:
        dependencies:
          - systemd

release:
  disable: true # this disables releasing *to GitHub*; it will still push to Docker
  # (we want Releaser to be responsible for doing all the GitHub release manipulations)

dockers:
  - image_templates:
      - "launchdarkly/ld-relay:v{{ .Major }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    skip_push: '{{ ne .Env.LD_RELEASER_UPDATE_MAJOR "true" }}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  - image_templates:
      - "launchdarkly/ld-relay:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    skip_push: '{{ ne .Env.LD_RELEASER_UPDATE_LATEST "true" }}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: "launchdarkly/ld-relay:v{{ .Major }}"
    skip_push: '{{ ne .Env.LD_RELEASER_UPDATE_MAJOR "true" }}'
    image_templates:
      - "launchdarkly/ld-relay:v{{ .Major }}-amd64"

  - name_template: "launchdarkly/ld-relay:latest"
    skip_push: '{{ ne .Env.LD_RELEASER_UPDATE_LATEST "true" }}'
    image_templates:
      - "launchdarkly/ld-relay:latest-amd64"

  # We'll also create aliases for the Alpine-based image with the suffix "-alpine" to make it easier to distinguish
  # from the debian12 image. This will also allow us to eventually deprecate the non-suffixed tags in a future major version.
  - name_template: "launchdarkly/ld-relay:{{ .Version}}-alpine"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-amd64"

  - name_template: "launchdarkly/ld-relay:v{{ .Major }}-alpine"
    skip_push: '{{ ne .Env.LD_RELEASER_UPDATE_MAJOR "true" }}'
    image_templates:
      - "launchdarkly/ld-relay:v{{ .Major }}-amd64"

  - name_template: "launchdarkly/ld-relay:latest-alpine"
    skip_push: '{{ ne .Env.LD_RELEASER_UPDATE_LATEST "true" }}'
    image_templates:
      - "launchdarkly/ld-relay:latest-amd64"
