project_name: ld-relay

builds:
- env:
  - CGO_ENABLED=0
  main: .
  binary: ld-relay
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}`.
  ldflags:
  - -s -w -X internal.version.Version={{.Version}}
  goos: # Goreleaser's default for this is darwin + linux, but let's be explicit
    - darwin
    - linux
  goarch: # Goreleaser's default for this is 386 + amd64, but let's be explicit
    - '386'
    - amd64
    - arm
    - arm64
  goarm:
    - "7"
  ignore: # Go 1.15+ doesn't support 32-bit Darwin
    - goos: darwin
      goarch: '386'

nfpms:
  -
    file_name_template: >-
      {{ .ConventionalFileName }}
    homepage: https://launchdarkly.com/
    maintainer: LaunchDarkly <team@launchdarkly.com>
    description: LaunchDarkly Stream Relay Proxy
    license: Apache 2.0
    vendor: Catamorphic Co.

    formats:
    - deb
    - rpm

    contents:
      - src: linux/etc/ld-relay.conf
        dst: /etc/ld-relay.conf
        type: config

      - src: linux/etc/init/ld-relay.conf
        dst: /etc/init/ld-relay.conf
        packager: deb

      - src: linux/etc/system/ld-relay.service
        dst: /usr/lib/systemd/system/ld-relay.service
        packager: rpm


    overrides:
      deb:
        dependencies:
        - upstart
      rpm:
        dependencies:
        - systemd

release:
  disable: true # this disables releasing *to GitHub*; it will still push to Docker
  # (we want Releaser to be responsible for doing all the GitHub release manipulations)

dockers:
  # The following templates are for the Alpine-based image.
  # i386
  - image_templates:
    - "launchdarkly/ld-relay:{{ .Version }}-i386"
    - "launchdarkly/ld-relay:v{{ .Major }}-i386"
    - "launchdarkly/ld-relay:latest-i386"
    use: buildx
    goos: linux
    goarch: '386'
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--platform=linux/386"

  # AMD64
  - image_templates:
    - "launchdarkly/ld-relay:{{ .Version }}-amd64"
    - "launchdarkly/ld-relay:v{{ .Major }}-amd64"
    - "launchdarkly/ld-relay:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"

  # ARMv7
  - image_templates:
    - "launchdarkly/ld-relay:{{ .Version }}-armv7"
    - "launchdarkly/ld-relay:v{{ .Major }}-armv7"
    - "launchdarkly/ld-relay:latest-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"

  # ARM64v8
  - image_templates:
    - "launchdarkly/ld-relay:{{ .Version }}-arm64v8"
    - "launchdarkly/ld-relay:v{{ .Major }}-arm64v8"
    - "launchdarkly/ld-relay:latest-arm64v8"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"

  ## The following image templates are for the nonroot debian12 distroless image.

  # AMD64
  - image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:latest-nonroot-static-debian12-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-nonroot-static-debian12.goreleaser
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  # ARMv7
  - image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:latest-nonroot-static-debian12-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile-nonroot-static-debian12.goreleaser
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"

  # ARM64v8
  - image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-nonroot-static-debian12-arm64v8"
      - "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12-arm64v8"
      - "launchdarkly/ld-relay:latest-nonroot-static-debian12-arm64v8"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile-nonroot-static-debian12.goreleaser
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"

  ## The following image templates are for the debug nonroot debian12 distroless image. This image is
  ## necessary to get a shell in the container for debugging purposes.

  # AMD64
  - image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-debug-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-debug-nonroot-static-debian12.goreleaser
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  # ARMv7
  - image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-debug-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile-debug-nonroot-static-debian12.goreleaser
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"

  # ARM64v8
  - image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-debug-nonroot-static-debian12-arm64v8"
      - "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12-arm64v8"
      - "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12-arm64v8"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile-debug-nonroot-static-debian12.goreleaser
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"

docker_manifests:
  # For the Alpine image
  - name_template: "launchdarkly/ld-relay:{{ .Version}}"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-amd64"
      - "launchdarkly/ld-relay:{{ .Version }}-armv7"
      - "launchdarkly/ld-relay:{{ .Version }}-arm64v8"
      - "launchdarkly/ld-relay:{{ .Version }}-i386"

  - name_template: "launchdarkly/ld-relay:v{{ .Major }}"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:v{{ .Major }}-amd64"
      - "launchdarkly/ld-relay:v{{ .Major }}-armv7"
      - "launchdarkly/ld-relay:v{{ .Major }}-arm64v8"
      - "launchdarkly/ld-relay:v{{ .Major }}-i386"

  - name_template: "launchdarkly/ld-relay:latest"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:latest-amd64"
      - "launchdarkly/ld-relay:latest-armv7"
      - "launchdarkly/ld-relay:latest-arm64v8"
      - "launchdarkly/ld-relay:latest-i386"

  # For the static debian12 image
  - name_template: "launchdarkly/ld-relay:latest-nonroot-static-debian12"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:latest-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:latest-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:latest-nonroot-static-debian12-arm64v8"

  - name_template: "launchdarkly/ld-relay:{{ .Version}}-nonroot-static-debian12"
    skip_push: false
    image_templates:
       - "launchdarkly/ld-relay:{{ .Version }}-nonroot-static-debian12-amd64"
       - "launchdarkly/ld-relay:{{ .Version }}-nonroot-static-debian12-armv7"
       - "launchdarkly/ld-relay:{{ .Version }}-nonroot-static-debian12-arm64v8"

  - name_template: "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:v{{ .Major }}-nonroot-static-debian12-arm64v8"

  # For the debug static debian12 image
  - name_template: "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:latest-debug-nonroot-static-debian12-arm64v8"

  - name_template: "launchdarkly/ld-relay:{{ .Version}}-debug-nonroot-static-debian12"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:{{ .Version }}-debug-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:{{ .Version }}-debug-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:{{ .Version }}-debug-nonroot-static-debian12-arm64v8"

  - name_template: "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12"
    skip_push: false
    image_templates:
      - "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12-amd64"
      - "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12-armv7"
      - "launchdarkly/ld-relay:v{{ .Major }}-debug-nonroot-static-debian12-arm64v8"
