project_name: ld-relay

builds:
- env:
  - CGO_ENABLED=0
  main: .
  binary: ld-relay
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}`.
  ldflags:
  - -s -w -X internal.version.Version={{.Version}}
  goos: # Goreleaser's default for this is darwin + linux, but let's be explicit
    - darwin
    - linux
  goarch: # Goreleaser's default for this is 386 + amd64, but let's be explicit
    - 386
    - amd64
  ignore: # Go 1.15+ doesn't support 32-bit Darwin
    - goos: darwin
      goarch: 386

nfpms:
  -
    file_name_template: "{{ .ProjectName }}_{{ .Version }}.{{ .ShortCommit }}_{{ .Arch }}"

    homepage: https://launchdarkly.com/
    maintainer: LaunchDarkly <team@launchdarkly.com>
    description: LaunchDarkly Stream Relay Proxy
    license: Apache 2.0
    vendor: Catamorphic Co.

    formats:
    - deb
    - rpm

    replacements:
      386: i386

    config_files:
      "linux/etc/ld-relay.conf": "/etc/ld-relay.conf"

    overrides:
      deb:
        dependencies:
        - upstart
        files:
          "linux/etc/init/ld-relay.conf": "/etc/init/ld-relay.conf"
      rpm:
        dependencies:
        - systemd
        files:
          "linux/etc/system/ld-relay.service": "/usr/lib/systemd/system/ld-relay.service"

release:
  disable: true # this disables releasing *to GitHub*; it will still push to Docker
  # (we want Releaser to be responsible for doing all the GitHub release manipulations)

dockers:
  - image_templates:
    - "launchdarkly/ld-relay:{{ .Tag }}"
    - "launchdarkly/ld-relay:v{{ .Major }}"
    - "launchdarkly/ld-relay:latest"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    skip_push: false
    # If your Dockerfile copies files other than the binary itself,
    # you should list them here as well.
    # extra_files:
    # - filename
