FROM alpine:3.6

RUN apk --no-cache add \
    go \
    libc-dev \
 && rm -rf /var/cache/apk/*

RUN mkdir -p /go/src/github.com/launchdarkly/ld-relay

WORKDIR /go/src/github.com/launchdarkly/ld-relay

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOPATH=/go

RUN go build -a -installsuffix cgo -o ldr

CMD ["/bin/true"]
