version: "2"

services:
  relay-debian:
    build:
      context: .
      dockerfile: Dockerfile.debian-test
    privileged: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  relay-centos:
    build:
      context: .
      dockerfile: Dockerfile.centos-test
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  relay-docker:
    image: launchdarkly/ld-relay
    env_file:
      - smoke-test.env

  relay-docker-standalone:
    build: .
    env_file:
      - smoke-test.env

  test-centos:
    image: cimg/go:1.13
    command: bash -c "dockerize -wait http://relay-centos:8030/status -timeout 5s; curl http://relay-centos:8030/status"

  test-debian:
    image: cimg/go:1.13
    command: bash -c "dockerize -wait http://relay-debian:8030/status -timeout 5s; curl http://relay-debian:8030/status"

  test-docker:
    image: cimg/go:1.13
    command: bash -c "dockerize -wait http://relay-docker:8030/status -timeout 5s; curl http://relay-docker:8030/status"

  test-docker-standalone:
    image: cimg/go:1.13
    command: bash -c "dockerize -wait http://relay-docker:8030/status -timeout 5s; curl http://relay-docker-standalone:8030/status"
