name: Publish Artifacts
description: 'Publish artifacts to Github Release'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  dry-run:
    description: 'Is this a dry run. If so no package will be published.'
    required: false
    default: 'true'
  tag:
    description: 'Tag to upload artifacts to.'
    required: true
  update-major-tag:
    description: "Should vX.Y.Z be tagged as 'vX' in Dockerhub?"
    required: false
    default: 'false'
  update-latest-tag:
    description: "Should vX.Y.Z be tagged as 'latest' in Dockerhub?"
    required: false
    default: 'false'
outputs:
  checksum_file:
    description: path to the sha256 checksums file
    value: ${{ steps.binary.outputs.checksum_file }}
  images_and_digests:
    description: built docker image names and digests in JSON format
    value: ${{ steps.image.outputs.images_and_digests }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/386
    - name: Login to Docker
      if: inputs.dry-run != 'true'
      shell: bash
      run: |
        echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Build release artifacts
      shell: bash
      env:
        LD_RELEASER_UPDATE_MAJOR: ${{ inputs.update-major-tag }}
        LD_RELEASER_UPDATE_LATEST: ${{ inputs.update-latest-tag }}
      run: |
        TAG="${{ inputs.tag }}"
        VERSION="${TAG#v}"
        ./scripts/release.sh ${{ inputs.dry-run == 'true' && '--dry-run' || '' }} "$VERSION"

    - name: Output checksum file path
      id: binary
      shell: bash
      run: |
        echo "checksum_file=dist/checksums.txt" >> "$GITHUB_OUTPUT"

    - name: Output image and digest
      id: image
      shell: bash
      run: |
        if [[ -f dist/images_and_digests.json ]]; then
          echo "images_and_digests=$(cat dist/images_and_digests.json)" >> "$GITHUB_OUTPUT"
        else
          echo "images_and_digests=[]" >> "$GITHUB_OUTPUT"
        fi

    - name: Upload Release Artifacts
      if: inputs.dry-run != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh release upload ${{ inputs.tag }} ./dist/*.deb ./dist/*.rpm ./dist/*.tar.gz ./dist/*.txt --clobber
