name: Publish Artifacts
description: 'Publish artifacts to Github Release'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  dry-run:
    description: 'Is this a dry run. If so no package will be published.'
    required: false
    default: 'true'
  tag:
    description: 'Tag to upload artifacts to.'
    required: true
outputs:
  hashes: 
    description: sha256sum hashes of built artifacts 
    value: ${{ steps.binary.outputs.hashes }}
  images_and_digests: 
    description: built docker image names and digests in JSON format
    value: ${{ steps.image.outputs.images_and_digests }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/386
    - name: Git clean
      shell: bash
      run: git clean -f
    - name: Login to Docker
      shell: bash
      run: |
        echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - name: Run Goreleaser
      id: goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --clean ${{ inputs.dry-run == 'true' && '--skip=publish' || '' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - name: Generate binary hashes
      id: binary 
      shell: bash
      env: 
        ARTIFACTS: ${{ steps.goreleaser.outputs.artifacts }}
      run: |
        # Generate binary hashes
        set -euo pipefail

        checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
        echo "hashes=$(cat $checksum_file | base64 -w0)" >> "$GITHUB_OUTPUT"
    - name: Output image and digest
      id: image
      shell: bash
      env:
        ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
      run: |
        # Generate image digest
        set -euo pipefail
        echo "images_and_digests=$(echo "$ARTIFACTS" | jq -c '. | map(select (.type=="Docker Manifest") | .image=(.path | split(":")[0]) | .digest=(.extra | .Digest) | {image, digest})')" >> "$GITHUB_OUTPUT"

    - name: Upload Release Artifacts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh release upload ${{ inputs.tag }} ./dist/*.deb ./dist/*.rpm ./dist/*.tar.gz ./dist/*.txt --clobber
