name: Check Supported Go Versions
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  check-go-versions:
    permissions:
      contents: write
      pull-requests: write
    uses: launchdarkly/gh-actions/.github/workflows/sdk-go-versions.yml@main
    with:
      branches: '["v8"]'
      precision: latest
      pr_title_prefix: fix(deps)
      update_script: ./scripts/update-go-release-version.sh
      add_paths: |
        Dockerfile
        .github/variables/go-versions.env
