name: Common CI
on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use for the jobs."
        required: true
        type: string

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: 'Unit Tests'
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-tests
        with:
          go-version: ${{ inputs.go-version }}
          lint: 'true'
          coverage: 'true'

      - name: Prometheus Endpoint Test
        shell: bash
        run: ./scripts/test-prometheus-endpoint.sh

  benchmarks:
    name: 'Benchmarks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/benchmarks
        with:
          go-version: ${{ inputs.go-version }}
