name: Security Scan

on:
  workflow_dispatch:
    inputs:
      docker-image:
        description: 'The image. Defaults to launchdarkly/ld-relay:v7.'
        type: string
        required: false

  schedule:
    - cron: "0 8 * * *"

jobs:
  scan-relay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine image
        id: image
        env:
          IMAGE: ${{ inputs.docker-image }}
        run: |
          echo "value=${IMAGE:-launchdarkly/ld-relay:v7}" >> $GITHUB_OUTPUT

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image.outputs.value }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
