name: Security Scan (Alpine)

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scan-relay:
    strategy:
      matrix:
        tag: ['latest', 'latest-alpine', 'v8', 'v8-alpine']
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de # v1.18.2
        with:
          command: cves
          image: launchdarkly/ld-relay:${{ matrix.tag }}
          exit-code: true
          only-fixed: true
          write-comment: false
          dockerhub-user: ${{ vars.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_RO_TOKEN }}
