name: Security Scan
on:
  workflow_dispatch:
    inputs:
      docker-image:
        description: "The Docker image to scan."
        required: false

  schedule:
    - cron: "0 8 * * *"

jobs:
  scan-relay:
    name: ${{ format('Trivy Scan of Docker Image ({0})', inputs.docker-image || 'launchdarkly/relay:latest') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.docker-image || 'launchdarkly/relay:latest' }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
