name: Security Scan (Alpine)

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scan-relay:
    strategy:
      matrix:
        tag: ['latest', 'latest-alpine', 'v8', 'v8-alpine']
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: 'Get Docker token'
        uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/global/services/docker/public/username = DOCKER_USERNAME, /global/services/docker/public/token = DOCKER_TOKEN'
      - uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de # v1.18.2
        with:
          command: cves
          image: launchdarkly/ld-relay:${{ matrix.tag }}
          exit-code: true
          only-fixed: true
          write-comment: false
          dockerhub-user: ${{ env.DOCKER_USERNAME }}
          dockerhub-password: ${{ env.DOCKER_TOKEN }}
