name: 'Daily Integration Tests'
on:
  workflow_dispatch:
    inputs:
      go-version:
        description: "Go version to use for building Relay (leave empty for latest defined in repo.)"
        required: false
        type: string

  schedule:
    - cron: "0 8 * * *"

jobs:
  go-versions:
    uses: ./.github/workflows/go-versions.yml

  integration-test:
    needs: go-versions
    strategy:
      fail-fast: false
      matrix:
        environment: ['staging', 'production']
        branch: ['v7', 'v8']

    uses: ./.github/workflows/integration-test.yml
    with:
      environment: ${{ matrix.environment }}
      go-version: ${{ inputs.go-version != '' && inputs.go-version || needs.go-versions.outputs.latest }}
      branch: ${{ matrix.branch }}
