name: Security Scan (Alpine)

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scan-relay:
    strategy:
      matrix:
        tag: ['latest', 'latest-alpine', 'v7', 'v8', 'v8-alpine']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        env:
          # Avoid rate-limiting on ghcr.io (https://github.com/aquasecurity/trivy-action/issues/389)
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        with:
          image-ref: launchdarkly/ld-relay:${{ matrix.tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
