name: Security Scan

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scan-relay:
    strategy:
      matrix:
        tag: ['latest', 'v7', 'v8']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: launchdarkly/ld-relay:${{ matrix.tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
