name: Publish Images and Artifacts
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Skip publishing to DockerHub'
        type: boolean
        required: false
        default: true
      tag:
        description: 'Tag to upload binary artifacts to.'
        type: string
        required: true

jobs:
  go-versions:
    uses: ./.github/workflows/go-versions.yml

  build-publish:
    needs: go-versions
    runs-on: ubuntu-latest
    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          depth: 0
      - name: Build and Test
        uses: ./.github/actions/unit-tests
        with:
          go-version: ${{ needs.go-versions.outputs.latest }}
      - name: 'Get Docker token'
        uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.0.1
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/global/services/docker/public/username = DOCKER_USERNAME, /global/services/docker/public/token = DOCKER_TOKEN'
      - name: Publish Package
        uses: ./.github/actions/publish
        with:
          go-version: ${{ needs.go-versions.outputs.latest }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ inputs.dry_run }}
          tag: ${{ inputs.tag }}
